include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35512_wvga_dsi_vdo_txd")
obj-y   +=  nt35512_wvga_dsi_vdo_txd.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm8018b_wvga_dsi_vdo_dijing")
obj-y   +=  otm8018b_wvga_dsi_vdo_dijing.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm8019a_wvga_dsi_vdo_dijing")
obj-y   +=  otm8019a_wvga_dsi_vdo_dijing.o
endif
